// Application constants

// Pagination
const DEFAULT_PAGE = 1;
const DEFAULT_LIMIT = 10;
const MAX_LIMIT = 100;
const MAX_EXPORT_LIMIT = 10000;

// Search and filtering
const SEARCH_DEBOUNCE_MS = 300;

// OTP
const OTP_LENGTH = 6;
const OTP_EXPIRY_MINUTES = 10;

// Password reset
const PASSWORD_RESET_EXPIRY_MINUTES = 10;

// JWT
const DEFAULT_JWT_EXPIRE = '7d';
const REMEMBER_ME_JWT_EXPIRE = '30d';

// Rate limiting
const RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000; // 15 minutes
const RATE_LIMIT_MAX_REQUESTS = 100;
const AUTH_RATE_LIMIT_MAX_REQUESTS = 5;
const PASSWORD_RESET_RATE_LIMIT_MAX_REQUESTS = 3;
const OTP_RATE_LIMIT_MAX_REQUESTS = 3;

// File uploads
const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB

// Database
const DB_CONNECTION_RETRIES = 5;
const DB_RETRY_DELAY_MS = 5000;

// Cursor tracking
const MAX_CURSOR_MOVEMENTS = 100;
const BOT_DETECTION_THRESHOLD = 80;

module.exports = {
  DEFAULT_PAGE,
  DEFAULT_LIMIT,
  MAX_LIMIT,
  MAX_EXPORT_LIMIT,
  SEARCH_DEBOUNCE_MS,
  OTP_LENGTH,
  OTP_EXPIRY_MINUTES,
  PASSWORD_RESET_EXPIRY_MINUTES,
  DEFAULT_JWT_EXPIRE,
  REMEMBER_ME_JWT_EXPIRE,
  RATE_LIMIT_WINDOW_MS,
  RATE_LIMIT_MAX_REQUESTS,
  AUTH_RATE_LIMIT_MAX_REQUESTS,
  PASSWORD_RESET_RATE_LIMIT_MAX_REQUESTS,
  OTP_RATE_LIMIT_MAX_REQUESTS,
  MAX_FILE_SIZE,
  DB_CONNECTION_RETRIES,
  DB_RETRY_DELAY_MS,
  MAX_CURSOR_MOVEMENTS,
  BOT_DETECTION_THRESHOLD,
};
